language: java

jdk:
- oraclejdk8

after_success:
- .buildscript/deploy_snapshot.sh

env:
  global:
  - secure: "oVqM6xkzgW9dpxpP7M6OJB2rjnS+RH3NA2CFHtwV7+5F9o/zpU+KnMphGxEyrKzVQYscoj+sQ8vHIWeKcsDpjhoiYvRqffu7sBWu+y1nuPbQfnl0uiUKS3NyUyT6jNFmouv7FQwuQtFY3jgB9ZWAqcHYvstJk5CDhvhjqKNcrQtqCe16k1lU2Sm9k2x22jNrzrKOXHeyl0OGcdBsmmgODTPFCZ+YW1PaVwJXAcQy1A86s75htT5TSpkw4kzCQSgFTnRIQ4H5FbsesMKEuS144Hapn+dVJDW+WCC3leiFQD0AZqLkmnG5i910OH5GiOUx4uRu7vJci5OJYZRZ/KBKnnoZQU5jrZHFdvoWmNfiAL8GVR1ADtCMw14ocZD9pUk+4wqc/iOM5wPEzm4OuPEadlD4cStY0ZNE4t8jtbWDBN2yQNl2FuZeWbs6mfl0idsnJeqWTm1DK/7C5VMuUsxMRc4SgGk0iQvXzPvEP5whzREkhuqDRWFT6VosCJQzGq4PdvfIKq0bnq9GCLO/WHf5wckjH1nt8FOeppyPw5xsJezETqG8PdvOyv+sfFmwy/n2k+I7UMz9cwlKR7cctoqsywK7aQxjbPpN/HUpfCfsUCZ4/RpmswCOWENsEKi+RYxISEVrw++OQy9ziQJwO8sapZRla13UZh7q3tSTGY0FaEY="
  - secure: "lgsyfyv14nj+ykzmyUQaWveKU8o2iJghEXXOfqsB83MBTiUPaoXPqsg5hCmFjLdlFOqNMgjiOuyNwg7yxYws8bHBGfwlXBvdb8fjW7I6a2kUbm/l9qJBDizbLBFFLDYCEQ7qqC3bkTU7jNSgPoxuiZcN918myWq+/wqnOtdItbt2rnohbdmjI8TZnXIR4RRzk9txVshPB4GoICezl7D/9t4s7+f9u6GhmrjO0Cm1oeOmnRskBBS4bgXhFKEIvlpSeedw3QUazhh7p9WhIIR6fAKoZ4fRpUbb14F3HeCI/3e0mMPdhMsXVxG2k4VRZOIi09DF0mYxX1x3wgZzT9hwu+fuXGB0ny2ia/EzfmE/S06GJcBcfYJa+L3mHxENyYFhnaccQMhjSpqKpODUZVotg8Du5EC4pjzWyj0XY9QQLivXOdS+tPgrBo+cyrZFbFPtfD1MqJ3XJ8MFvlqQ3wEiar3x+JxJ5pfUmGD6YZaHZwcDVjNV49xD9trYshdeQ3fLAdmMVQ+6KiPqaSGqRPlVxTWDAk30ZkZ65jr5lorot7JQPe21GwQzAAfw5TH2rzajPJ2WRKGjaNiyW6SVPG+4CFWAaSV5jWE/L4gM7GLv4z6jvUVxOHEqUG4sLjygFsS5mNNjLPKNxwv6bkmOct7q+119KR7YHZ2BGBxxIU6RBys="

notifications:
  email: false

sudo: false

cache:
  directories:
  - $HOME/.m2